### ISSUE TITLE
GARD Error

### ISSUE THREAD

**Issue by skyungyong** [veg/hyphy#1077]
Dear developers, 

I am running GARD on my local computer using the following commend: 

mpirun --hostfile hostfile -np 10 HYPHYMPI gard --type codon --alignment OG334.fa

The file includes 16 sequences and 3981 sites. GARD runs without any errors in Datamonkey (5e4623e4e44b9833be17c210). On my computer, however, GARD gives these error messages.

> >Loaded a codon multiple sequence alignment with **16** sequences, **1327** sites (65 of which are variable) from `OG344.fa`
> >Minimum size of a partition is set to be 29 sites
> 
> 
> ### Fitting the baseline (single-partition; no breakpoints) model
> * Log(L) = -5903.77, AIC-c = 11898.63 (44 estimated parameters)
> 
> ### Performing an exhaustive single breakpoint analysis
> Breakpoint          1 of 64. Best cAIC =   11898.6256
> ..
> Breakpoint         64 of 64. Best cAIC =   11898.6256 
> Done with single breakpoint analysis.
>    Best sinlge break point location: 950
>    c-AIC  = 11933.04111858161
> 
> ### Performing multi breakpoint analysis using a genetic algorithm
> 2 breakpoints [ generation      1, total models       63]. Min (c-AIC) =   11983.6922 [no improvement]
> ..
> ..
> [GARD]   2 breakpoints [ generation     60, total models      179]. Min (c-AIC) =   11988.0423 [no improvement], 
> Error:
> 
> Master node received an error:User-defined function 'gard.GA.initializeModels' needs 4 parameters, but 3 were supplied .
> 
> Function call stack
> 1 :  [namespace = gard] parentModels=gard.GA.initializeModels(numberOfBreakPointsBeingEvaluated,populationSize,numberOfPotentialBreakPoints);
> 
> -------
> 2 :  namespace
> 
> Step 0.populationSize=32;
> 
> Step 1.Branch under condition 'populationSize<mpi.NodeCount()-1'
>         to
>                 populationSize=mpi.NodeCount()+1;
>         else
>                 mutationRate=0.8;
> 
> Step 2.populationSize=mpi.NodeCount()+1;
> 
> Step 3.mutationRate=0.8;
> 
> Step 4.rateOfMutationsTharAreSmallShifts=0.5;
> 
> Step 5.maxFailedAttemptsToMakeNewModel=7;
> 
> Step 6.cAIC_diversityThreshold=0.001;
> 
> Step 7.cAIC_improvementThreshold=0.01;
> 
> Step 8.maxGenerationsAllowedWithNoNewModelsAdded=10;
> 
> Step 9.maxGenerationsAllowedAtStagnant_cAIC=100;
> 
> Step 10.addingBreakPointsImproves_cAIC=TRUE;
> 
> Step 11.numberOfBreakPointsBeingEvaluated=1;
> 
> Step 12.Branch under condition 'addingBreakPointsImproves_cAIC'
>         to
>                 numberOfBreakPointsBeingEvaluated+=1;
>         else
>                 <END EXECUTION>
> 
> Step 13.numberOfBreakPointsBeingEvaluated+=1;
> 
> Step 14.generationsAtCurrentBest_cAIC=0;
> 
> Step 15.generationsNoNewModelsAdded=0;
> 
> Step 16.parentModels=gard.GA.initializeModels(numberOfBreakPointsBeingEvaluated,populationSize,numberOfPotentialBreakPoints,bestOverallModelSoFar);
> 
> Step 17.terminationCondition=FALSE;
> 
> Step 18.generation=0;
> 
> Step 19.Branch under condition 'terminationCondition==FALSE'
>         to
>                 childModels=gard.GA.recombineModels(parentModels,populationSize);
>         else
>                 io.ClearProgressBar();
> 
> Step 20.childModels=gard.GA.recombineModels(parentModels,populationSize);
> 
> Step 21.interGenerationalModels=parentModels;
> 
> Step 22.interGenerationalModels*childModels;
> 
> Step 23.gard.GA.evaluateModels(interGenerationalModels);
> 
> 
> Step 27.Go to step 29
> 
> Step 28.generationsNoNewModelsAdded=0;
> 
> Step 29.Branch under condition '(math.minNormalizedRange(selectedModels)<cAIC_diversityThreshold)||(generationsNoNewModelsAdded>maxGenerationsAllowedWithNoNewModelsAdded)'
>         to
>                 parentModels=gard.GA.generateNewGenerationOfModelsByMutatingModelSet(parentModels,numberOfPotentialBreakPoints,mutationRate,rateOfMutationsTharAreSmallShifts);
>         else
>                 parentModels=selectedModels;
> 
> Step 30.parentModels=gard.GA.generateNewGenerationOfModelsByMutatingModelSet(parentModels,numberOfPotentialBreakPoints,mutationRate,rateOfMutationsTharAreSmallShifts);
> 
> Step 31.Branch under condition 'Abs(parentModels)==1'
>         to
>                 parentModels=gard.GA.initializeModels(numberOfBreakPointsBeingEvaluated,populationSize,numberOfPotentialBreakPoints);
>         else
>                 differenceThreshold=numberOfBreakPointsBeingEvaluated/4;
> 
> Step 32.parentModels=gard.GA.initializeModels(numberOfBreakPointsBeingEvaluated,populationSize,numberOfPotentialBreakPoints);
> 
> Step 33.differenceThreshold=numberOfBreakPointsBeingEvaluated/4;
> 
> Step 34.Go to step 36
> 
> Step 35.parentModels=selectedModels;
> 
> Step 36.currentBest_individual=Min(interGenerationalModels,1);
> 
> Step 37.currentBest_cAIC=currentBest_individual["value"];
> 
> Step 38.currentBest_model=Eval(currentBest_individual["key"]);
> 
> Step 39.Branch under condition 'previousBest_cAIC-currentBest_cAIC<cAIC_improvementThreshold'
>         to
>                 generationsAtCurrentBest_cAIC+=1;
>         else
>                 generationsAtCurrentBest_cAIC=0;
> 
> Step 40.generationsAtCurrentBest_cAIC+=1;
> 
> Step 41.Branch under condition 'generationsAtCurrentBest_cAIC>=maxGenerationsAllowedAtStagnant_cAIC'
>         to
>                 terminationCondition=TRUE;
>         else
>                 Go to step 45
> 
> Step 42.terminationCondition=TRUE;
> 
> Step 43.Go to step 45
> 
> Step 44.generationsAtCurrentBest_cAIC=0;
> 
> Step 45.previousBest_cAIC=currentBest_cAIC;
> 
> Step 46.generation+=1;
> 
> Step 47.Branch under condition 'bestOverall_cAIC_soFar-currentBest_cAIC>0'
>         to
>                 io.ReportProgressBar("GARD",Format(numberOfBreakPointsBeingEvaluated,3,0)+' breakpoints [ generation '+Format(generation,6,0)+", total models "+Format(Abs(masterList),8,0)+"]"+". Min (c-AIC) = "+Format(currentBest_cAIC,12,4)+" [ delta = "+Format(bestOverall_cAIC_soFar-currentBest_cAIC,8,2)+"], breakpoints at "+Join(", ",currentBest_model));
>         else
>                 io.ReportProgressBar("GARD",Format(numberOfBreakPointsBeingEvaluated,3,0)+' breakpoints [ generation '+Format(generation,6,0)+", total models "+Format(Abs(masterList),8,0)+"]"+". Min (c-AIC) = "+Format(currentBest_cAIC,12,4)+" [no improvement], breakpoints at "+Join(", ",bestOverallModelSoFar));
> 
> Step 48.io.ReportProgressBar("GARD",Format(numberOfBreakPointsBeingEvaluated,3,0)+' breakpoints [ generation '+Format(generation,6,0)+", total models "+Format(Abs(masterList),8,0)+"]"+". Min (c-AIC) = "+Format(currentBest_cAIC,12,4)+" [ delta = "+Format(bestOverall_cAIC_soFar-currentBest_cAIC,8,2)+"], breakpoints at "+Join(", ",currentBest_model));
> 
> Step 49.Go to step 51
> 
> Step 50.io.ReportProgressBar("GARD",Format(numberOfBreakPointsBeingEvaluated,3,0)+' breakpoints [ generation '+Format(generation,6,0)+", total models "+Format(Abs(masterList),8,0)+"]"+". Min (c-AIC) = "+Format(currentBest_cAIC,12,4)+" [no improvement], breakpoints at "+Join(", ",bestOverallModelSoFar));
> 
> Step 51.Go to step 19
> 
> Step 52.io.ClearProgressBar();
> 
> Step 53.statusString=("Done with "+numberOfBreakPointsBeingEvaluated+" breakpoint analysis.\n"+gard.GA.getMultiBreakPointStatusString(selectedModels,variableSiteMap));
> 
> Step 54.io.ReportProgressMessageMD('GARD','multi-breakpoint',statusString);
> 
> Step 55.Branch under condition 'previousBest_cAIC<bestOverall_cAIC_soFar'
>         to
>                 bestModel=gard.Helper.convertMatrixStringToMatrix(utility.Keys(selectedModels)[Min(utility.Values(selectedModels),1)[1]]);
>         else
>                 addingBreakPointsImproves_cAIC=FALSE;
> 
> Step 56.bestModel=gard.Helper.convertMatrixStringToMatrix(utility.Keys(selectedModels)[Min(utility.Values(selectedModels),1)[1]]);
> 
> Step 57.improvements[numberOfBreakPointsBeingEvaluated-1]={"deltaAICc":bestOverall_cAIC_soFar-previousBest_cAIC,"breakpoints":bestModel};
> 
> Step 58.bestOverall_cAIC_soFar=previousBest_cAIC;
> 
> Step 59.bestModel=gard.Helper.convertMatrixStringToMatrix(utility.Keys(selectedModels)[Min(utility.Values(selectedModels),1)[1]]);
> 
> Step 60.bestOverallModelSoFar=bestModel;
> 
> Step 61.Go to step 64
> 
> Step 62.addingBreakPointsImproves_cAIC=FALSE;
> 
> Step 63.gard.concludeAnalysis(bestOverallModelSoFar);
> 
> Step 64.Go to step 12;
> -------
> --------------------------------------------------------------------------
> MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
> with errorcode 1.
> 
> NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
> You may or may not see output from other processes, depending on
> exactly when Open MPI kills them.
> --------------------------------------------------------------------------

In some other jobs that failed, the messages.log.mpinode0 included at the end:

> Initial parameter values
> 
> gard.tree.part_0.1322_070_TN_1_C_T1NL_GT.t = 0.0388869661941182
> gard.tree.part_0.1316_024_TN_2_C_T1NL_GT.t = 0.008829088560635256
> gard.tree.part_0.1330_036_TN_1_C_T1NL_GT.t = 0.003778351256074604
> gard.tree.part_0.Node10.t = 0.003791700248648888
> gard.tree.part_0.2663_029_TN_2_C_T1NL_GT.t = 0.003778351256074604
> gard.tree.part_0.Node9.t = 0.01591224370778395
> gard.tree.part_0.1716_043_TN_1_C_T1NL_GT.t = 1.229777893372652e-20
> gard.tree.part_0.2133_031_TN_1_C_T1NL_GT.t = 1.065031132657476e-20
> gard.tree.part_0.Node14.t = 0.000577706037889189
> gard.tree.part_0.Node8.t = 0
> gard.tree.part_0.Node6.t = 0.02093097725136272
> gard.tree.part_0.0411_027_TN_1_C_T1NL_GT.t = 0.003790087319678646
> gard.tree.part_0.1269_058_TN_1_C_T1NL_GT.t = 0.002522229493168017
> gard.tree.part_0.Node17.t = 0
> gard.tree.part_0.Node5.t = 0.002228381347717684
> gard.tree.part_0.0422_043_TN_1_C_T1NL_GT.t = 0.001357835660842507
> gard.tree.part_0.Node4.t = 0
> gard.tree.part_0.1039_055_TN_1_C_T1NL_GT.t = 0
> gard.tree.part_0.Node3.t = 0
> gard.tree.part_0.1404_089_TN_1_C_T1NL_GT.t = 0
> gard.tree.part_0.Node2.t = 0
> gard.tree.part_0.0483_064_TN_1_C_T1NL_GT.t = 0
> gard.tree.part_0.Node1.t = 0
> gard.tree.part_0.0722_020_TN_1_C_T1NL_GT.t = 0
> gard.tree.part_0.Heinz_053_TN_1_C_T1NL_GT.t = 0
> gard.tree.part_0.Node25.t = 0
> gard.tree.part_0.1136_052_TN_1_C_T1NL_GT.t = 0.001357283698739094
> gard.tree.part_0.Node24.t = 0.001161457228695395
> gard.tree.part_0.1401_055_TN_1_C_T1NL_GT.t = 0.001395063279673936
> Optimization finished in 22 loop passes.
> 2542 likelihood evaluation calls and 4542 matrix exponentiations calls were made
> 
> ':shallow' is not a supported agrument type for DeleteObject(
> Variable 'USE_JSON_FOR_MATRIX' was not initialized prior to being used
> Node 0 is shutting down
> 
> PurgeAll was successful

Would you know why this is happening? Thank you so much in advance!

**Comment by spond** [comment]
Dear @skyungyong,

Thank you for reporting this issue. It is a stochastically encountered error, which I fixed in d13627d6 (you can pull the `develop` branch to test it).

The error might also disappear if you simply rerun the analysis.

Best,
Sergei

**Comment by skyungyong** [comment]
Dear @spond,

Thank you for your quick follow-up! I tested with the new Gard.bf. It seems line 390 was changed accordingly:  parentModels = gard.GA.initializeModels(numberOfBreakPointsBeingEvaluated, populationSize, numberOfPotentialBreakPoints, bestOverallModelSoFar);


However, I still see the error message after predicting two break points. 

> ### Performing multi breakpoint analysis using a genetic algorithm
> [GARD]   2 breakpoints [ generation     16, total models       63]. Min (c-AIC) =   11254.6819 [no improvement], breakpoints at Error:
> 
> Master node received an error:User-defined function 'gard.GA.initializeModels' needs 4 parameters, but 3 were supplied .
> 
> Function call stack
> 1 :  [namespace = gard] parentModels=gard.GA.initializeModels(numberOfBreakPointsBeingEvaluated,populationSize,numberOfPotentialBreakPoints);
>         Standard input redirect:
>                 Empty Associative List

The message right below Functional call stack seems to be different from the previous one though. I was not be able to complete the process by rerunning it. 

Thank you for your help!

**Comment by spond** [comment]
Dear @skyungyong,

Did you do `make install`? If not, `HYPHYMPI` will refer to previous library files. You can specify 
```
LIBPATH=/path/to/hyphy/res/
```

on the command line to force the program to look for library files (like GARD) in the specific path (replace `/path/to/hyphy` with the path to where the HyPhy development branch repo is)

Best,
Sergei

**Comment by skyungyong** [comment]
Dear @spond,

I see! Now GARD continues without error messages! Thank you! I noticed that previously, the number of generation goes up to the total number of models and the program becomes terminated. Now GARD is at 258 generations with total models 65. Is this normal? 

> ### Performing multi breakpoint analysis using a genetic algorithm
> [GARD]   2 breakpoints [ generation    258, total models       65]. Min (c-AIC) =   11254.6819 [no improvement], breakpoints at

**Comment by spond** [comment]
Dear @skyungyong,

It looks like the sampling algorithm is simply not finding that many new models because there are too few variable sites in the alignment (65 variable sites). But it should exceed 65. Would you mind sending your alignment to me by e-mail (or posting it here if you are comfortable with that), so that I can debug the issue?

Best,
Sergei

**Comment by spond** [comment]
Dear @skyungyong,

Please try the current `develop` branch. There were bugs in the released GARD implementation in 2.5.x that might cause the algorithm to fail to converge or take too long to run.

Best,
Sergei
