### ISSUE TITLE
FUBAR LC_ALL error

### ISSUE THREAD

**Issue by Frazapel** [veg/hyphy#1168]
Hi all,

I am trying to run FUBAR on a mitochondrial gene. The matrix is formed by 37 sequences, 981 bases long. 
The job stops with this error:
```
-bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")
manpath: can't set the locale; make sure $LC_* and $LANG are correct
/bin/bash: warning: setlocale: LC_ALL: cannot change locale ("en_US.UTF-8")

```
I tried twice but the error is the same. 
Could you help me?

**Comment by Frazapel** [comment]
Yes I am sorry, I forgot to mention that I was using Datamonkey.
The 2 jobs IDs:
http://datamonkey.org/fubar/5ee14c665a2f585a5084bd6b
http://datamonkey.org/fubar/5ee14a0d5a2f585a5084bd3b

Thanks a lot for the quick response

**Comment by stephenshank** [comment]
Dear @Frazapel,

Thanks again for reporting. I've traced the issue. It turns out FUBAR is not picking up the genetic code after a recent update that was rushed out.

As a temporary fix, I've ran your data with the appropriate code. It appears as though you selected invertebrate mtDNA, and both links above are two runs of the same dataset... if not, please correct me. If my assumptions are correct, you may find your results here:
http://datamonkey.org/fubar/5ee14c665a2f585a5084bd6b

Leaving this issue open until a permanent fix is deployed (very soon).

Best,
Stephen

**Comment by Frazapel** [comment]
Thanks a lot! Yes it was the same dataset.

Thanks for the quick response and solution!

**Comment by stephenshank** [comment]
Dear @jordanz,

This was a bandaid fix for this particular job. The issue is still there (see discussion above). I still need to submit a PR to datamonkey-js-server (today) and deploy changes (Sunday, probably, so I can give ample notice on the warning banner since all jobs are lost with the type of change I have to make).

Best,
Stephen

**Comment by jzehr** [comment]
Dear @stephenshank,

Good to know! Thanks for that, this will remain an open issue then.

Best,
Jordan

**Comment by gubrins** [comment]
I think the problem is still present, I'm trying to run a mitochondrial dataset on FUBAR (http://datamonkey.org/fubar/5eeb5fd40f0bfa13c9b8b3ff) but it doesn't update.

Best,
Gabriel

**Comment by stephenshank** [comment]
Dear @gubrins,

The update was pushed today around 10 AM EST. Here is a invertebrate mtDNA dataset (with stop codons in the standard genetic code) that successfully ran: http://datamonkey.org/fubar/5eeb7dd864d1164953f089bb

Please try again and let me know if you experience any issues.

Best,
Stephen

**Comment by gubrins** [comment]
Everything is working now! Thank you very much!
